// <auto-generated />
using AtharsBot.DataModules;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtharsBot.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20240818220331_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("AtharsBot.DataModules.AthrModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isnad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mtn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sorce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AtherTable");
                });
#pragma warning restore 612, 618
        }
    }
}
