// <auto-generated />
using System;
using AtharsBot.DataModules;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtharsBot.Migrations
{
    [DbContext(typeof(Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("IslamReasearchBot.DataModules.Admins", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServerSettingID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ServerSettingID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("IslamReasearchBot.DataModules.AthrModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isnad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mtn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sorce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("AtherTable");
                });

            modelBuilder.Entity("IslamReasearchBot.DataModules.ServerSetting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannleID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ServerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("ServersTable");
                });

            modelBuilder.Entity("IslamReasearchBot.DataModules.Admins", b =>
                {
                    b.HasOne("IslamReasearchBot.DataModules.ServerSetting", null)
                        .WithMany("Admins")
                        .HasForeignKey("ServerSettingID");
                });

            modelBuilder.Entity("IslamReasearchBot.DataModules.ServerSetting", b =>
                {
                    b.Navigation("Admins");
                });
#pragma warning restore 612, 618
        }
    }
}
